name: learner-svc-build
on:
  push:
    branches:
      - main
    paths:
      - services/learner/**
      - packages/**
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/service-build
        with:
          service: learner-service
          tag: "edu-hub-learner-service:${{ github.sha }}-${{ github.run_attempt }}"
          access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
          repository_access_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}